const searchIndex = [
    { title: 'Workshop on Harmony', href: '/workshop' },
    { title: 'Philosophy of Coexistence', href: '/philosophy/in-brief' },
    { title: 'About the Initiative', href: '/about' },
    { title: 'Madhyasth Darshan', href: '/books' },
    { title: 'Philosophy', href: '/philosophy/in-brief' },
    { title: 'Books and Resources', href: '/books' },
    { title: 'Why Attend?', href: '/workshop' },
    { title: 'Life Topics', href: '/workshop' },
    { title: 'How is the Shivir', href: '/workshop' },
    { title: 'Gallery', href: '/workshop' },
    { title: 'Who we are?', href: '/workshop/facilitator-profiles' },
    { title: 'A Mining Engineer turned ', href: '/workshop/facilitator-profiles' },
    { title: 'See More Benefits', href: '/workshop/workshop-benefits' },
    { title: 'Typical Benefits of ', href: '/workshop/workshop-benefits' },
    { title: 'Download Pre Reading', href: '/workshop/download-pre-reading' },
    { title: 'To circulate', href: '/workshop/download-pre-reading' },
    { title: 'Invitation Posters', href: '/workshop/download-pre-reading' },
    { title: 'What is Madhyasth Darshan?', href: '/about' },
    { title: 'Unique Approach and Benefits', href: '/about' },
    { title: 'Practical Living and Solutions', href: '/about' },
    { title: 'Existence-based Human-Centric Thinking', href: '/about/authors-testimony' },
    { title: 'जीवन ज्ञान संबंधी अध्ययन', href: '/about/authors-testimony' },
    { title: 'Vision of Human Living', href: '/about/vision-for-world' },
    { title: 'Self Governing Family', href: '/about/vision-for-world' },
    { title: 'Impact in Education', href: '/about/impact-in-education-and-society' },
    { title: 'In Education / Academics', href: '/about/impact-in-education-and-society' },
    { title: 'Our Thinking for ', href: '/about/impact-in-education-and-society' },
    { title: 'In Brief', href: '/about/about-a-nagraj' },
    { title: 'Early Life', href: '/about/about-a-nagraj' },
    { title: 'Sadhana - Spiritual Practice', href: '/about/about-a-nagraj' },
    { title: 'The Jeevan Vidya Program', href: '/about/about-a-nagraj' },
    { title: 'Epilogue', href: '/about/about-a-nagraj' },
    { title: 'Read More', href: '/about/about-a-nagraj' },
    { title: 'Who We Are', href: '/about/about-us' },
    { title: 'Our Centres', href: '/about/our-centers' },
    { title: 'Important note for centres', href: '/about/our-centers' },
    { title: 'Contact Us', href: '/about/contact-us' },
    { title: 'Email Us', href: '/about/contact-us' },
    { title: 'Call Us', href: '/about/contact-us' },
    { title: 'Visit Us', href: '/about/contact-us' },
    { title: 'Saha-Astitva-vadi', href: '/philosophy/in-brief' },
    { title: 'Salient Points', href: '/philosophyin-brief' },
    { title: 'The Literature', href: '/philosophyin-brief' },
    { title: 'Proposal to humankind', href: '/philosophyin-brief' },
    { title: 'Background', href: '/philosophy/origins' },
    { title: 'Message to Humankind', href: '/philosophy/origins' },
    { title: ' Philosophy & Origins', href: '/philosophy/origins' },
    { title: 'Background', href: '/philosophy/concept-overview' },
    { title: 'Findings', href: '/philosophy/concept-overview' },
    { title: 'Nature of Human Living', href: '/philosophy/concept-overview' },
    { title: 'Summary', href: '/philosophy/concept-overview' },
    { title: 'Darshan Insights', href: '/philosophy/concept-overview' },
    { title: 'Key Philosophical Points', href: '/philosophy/key-discoveries' },
    { title: 'Discovery', href: '/philosophy/key-discoveries' },
    { title: 'See More Benefits', href: '/philosophy/key-discoveries' },
    { title: 'About Literature', href: '/philosophy/literature' },
    { title: '4 volumes fall under ', href: '/philosophy/literature' },
    { title: '3 volumes fall under', href: '/philosophy/literature' },
    { title: 'Shaastra: or Codes', href: '/philosophy/literature' },
    { title: 'Explore Concepts', href: '/philosophy/explore-concepts' },
    { title: '(translations) - by A.Nagraj', href: '/philosophy/explore-concepts' },
    { title: 'By Students', href: '/philosophy/explore-concepts' },
    { title: 'नागराजजी प्रमाणिक ग्रंथ', href: '/books' },
    { title: 'विडियो एवं ऑडियो', href: '/books' },
    { title: 'English & others', href: '/books/student-translations' },
    { title: 'Other Languages', href: '/books/student-translations' },
    { title: 'English Translated Versions', href: '/books/student-translations' },
    { title: 'Existence is Co-existence', href: '/' },
    { title: 'First time here', href: '/' },
    { title: 'Completed Intro Workshops', href: '/' },
    { title: 'Coexistentialism', href: '/' },
    { title: 'What is Madhyasth Darshan', href: '/' },
    { title: 'Need for this "Alternative"', href: '/' },
    { title: 'Navigate', href: '/' },
]

export default searchIndex;